server: 
  port: 8024
spring:  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #url: jdbc:mysql://192.168.0.11:3306/kjbBoard?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    url: jdbc:log4jdbc:mysql://192.168.0.11:3306/kjbBoard?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull    username: kjb
    password: 8325
mybatis: 
  type-aliases-package: com.kjb.kjbBoard.dto
custom: 
  genFileDirPath: C:/work/untact-teacher-file
  logging:
    dir: log
    level: info